### ISSUE TITLE
curl6 error

### ISSUE THREAD

**Issue by wetlyrics** [yobasystems/alpine-php-wordpress#1]
i test your stack on a docker swarm cluster behind traefik. before october everything was fine.
new update returns a curl6 error. wordpress admin seems slow using redis

# traefik.toml

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
# Uncomment the following two lines to redirect HTTP to HTTPS.
    [entryPoints.http.redirect]
    entryPoint = "https"
    regex = "^http://localhost/(.*)"
    replacement = "http://mydomain.com/$1"
    permanent = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/mydomain.com.crt"
      keyFile = "/etc/traefik/certs/mydomain.com.key"

# traefik deploy

docker service create -d --name loadbalancer \
--restart-condition any \
--replicas 1 \
--update-delay 2s \
--constraint=node.role==manager \
--publish 80:80 \
--publish 443:443 \
--publish 9090:8080 \
--mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
--mount type=bind,source=/mnt/efs/traefik/certs,target=/etc/traefik/certs \
--mount type=bind,source=/mnt/efs/traefik/traefik.toml,target=/etc/traefik/traefik.toml \
 --network net \
iloveuodi/traefik:v1.7.4-alpine \
--docker \
--docker.swarmmode \
--docker.watch \
--web \
--loglevel=DEBUG

# yobasystems stack

docker service create -d --name wordpress \
--hostname wordpress \
--limit-cpu 0.000 \
--limit-memory 170M \
--reserve-memory 30M \
--restart-condition any \
--replicas 1 \
--update-delay 2s \
--update-parallelism 1 \
--update-failure-action continue \
--restart-max-attempts 1 \
--constraint=node.role==worker \
--publish 8080:80 \
--label="traefik.frontend.headers.STSSeconds=15768000" \
--label="traefik.docker.network=net" \
--label="traefik.port=80" \
--label="traefik.frontend.rule=PathPrefix:/" \
--label="traefik.backend.loadbalancer.sticky=true" \
--mount type=bind,source=/mnt/efs/data/v1/html,target=/usr/html \
-e VIRTUAL_HOST=mydomain.com,www.mydomain.com \
  --network net \
iloveuodi/alpine-php-wordpress:cache

**Comment by dominictayloruk** [comment]
Seems strange as only aarch64 folder was added and the dates changed in the dockerfiles as you can see in the commit history.

**Comment by dominictayloruk** [comment]
See https://github.com/yobasystems/alpine-php-wordpress/issues/2
