### ISSUE TITLE
Duplicate dependency install

### ISSUE THREAD

**Issue by fluffy-kaiju** [yobasystems/alpine-php-wordpress#11]
Curl is installed twice on the same command

<img width="920" alt="image" src="https://github.com/yobasystems/alpine-php-wordpress/assets/57049713/714bcee5-432f-4a51-8456-1b559d7f1dcf">

https://github.com/yobasystems/alpine-php-wordpress/blob/982c87a8b81c598abb792e88aaa2bad80f14f812/alpine-php-wordpress-aarch64/Dockerfile#L36C16-L36C17

https://github.com/yobasystems/alpine-php-wordpress/blob/982c87a8b81c598abb792e88aaa2bad80f14f812/alpine-php-wordpress-amd64-s/Dockerfile#L38C83-L38C87

https://github.com/yobasystems/alpine-php-wordpress/blob/982c87a8b81c598abb792e88aaa2bad80f14f812/alpine-php-wordpress-amd64/Dockerfile#L36C83-L36C87

https://github.com/yobasystems/alpine-php-wordpress/blob/982c87a8b81c598abb792e88aaa2bad80f14f812/alpine-php-wordpress-armhf/Dockerfile#L36C83-L36C83

**Comment by dominictayloruk** [comment]
Good find, should be fixed after the new builds complete.
