### ISSUE TITLE
curl 6 error

### ISSUE THREAD

**Issue by wetlyrics** [yobasystems/alpine-php-wordpress#2]
i am running behinf traefik. iedit wp-config.php as you guys said running ubuntu 18.04
docker swarm.
after deploy your stack i got

Unable to reach WordPress.org at wordpress.org: cURL error 6: Could not resolve host: wordpress.org

**Comment by wetlyrics** [comment]
you bash into your alpine-php-wordpress container
run 
curl  -I gogle.com
output: curl: (6) Could not resolve host: google.com
do you know why??

same error on wordpress dashboard

**Comment by dominictayloruk** [comment]
> curl -I google.com

![screencapture-apps-stacks-1st47-services-1s108-containers-2018-12-02-14_11_43](https://user-images.githubusercontent.com/23389697/49340793-a4505980-f63c-11e8-884e-0a0144cf6467.png)


Might be your host.

Docker info?

**Comment by wetlyrics** [comment]
thanks for your first response
