### ISSUE TITLE
 directory index of "/usr/html/" is forbidden

### ISSUE THREAD

**Issue by qy2009** [yobasystems/alpine-php-wordpress#7]
what is the correct user ID and group ID I should use? 

I tried this one: 
The following user and group id are used, the files should be set to this: User ID: Group ID:

chown -R 100:101 /data/{domain}/html

E.G

chown -R 100:101 /data/yobasystems/html

it returned  directory index of "/usr/html/" is forbidden. 

then I tried set to my user ID which created the folder. failed as well.

**Comment by dominictayloruk** [comment]
Thats just the default nginx userid, you should really need to both just make sure the directory is writable
